Repository GreenByMe/GreenByMe_Server, pull requests merged in 2020-08, with the labels that each got.

#39 refactor: issue32
  src/main/java/org/greenbyme/angelhack/service/FileUploadDownloadService.java
  uploads/KakaoTalk_20190509_010954834.jpg
Labels: bug, fix

#43 release_2_0
  src/main/java/org/greenbyme/angelhack/config/ScheduledConfig.java
  src/main/java/org/greenbyme/angelhack/controller/MissionController.java
  src/main/java/org/greenbyme/angelhack/controller/PostController.java
  src/main/java/org/greenbyme/angelhack/controller/UserController.java
  src/main/java/org/greenbyme/angelhack/domain/PeriodScheduler.java
  src/main/java/org/greenbyme/angelhack/domain/mission/Mission.java
  src/main/java/org/greenbyme/angelhack/domain/missionInfo/MissionInfo.java
  src/main/java/org/greenbyme/angelhack/domain/missionInfo/MissionInfoRepository.java
  src/main/java/org/greenbyme/angelhack/domain/missionInfo/MissionInfoStatus.java
  src/main/java/org/greenbyme/angelhack/domain/missionInfo/RemainPeriod.java
  src/main/java/org/greenbyme/angelhack/exception/ErrorCode.java
  src/main/java/org/greenbyme/angelhack/service/FileUploadDownloadService.java
  src/main/java/org/greenbyme/angelhack/service/MissionInfoService.java
  src/main/java/org/greenbyme/angelhack/service/MissionService.java
  src/main/java/org/greenbyme/angelhack/service/PostService.java
  src/main/java/org/greenbyme/angelhack/service/UserService.java
  src/main/java/org/greenbyme/angelhack/service/dto/mission/MissionCertificationMethodRequestDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/mission/MissionSaveRequestDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/InProgressResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/MissionInfoDetailDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/MissionInfoDetailResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/MissionInfobyUserDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/post/PostSaveRequestDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/user/UserUpdatePhotoDto.java
  uploads/KakaoTalk_20190509_010954834.jpg
Labels: fixed

#65 Feat/issue57
  .gitignore
  src/main/java/org/greenbyme/angelhack/InitDB.java
  src/main/java/org/greenbyme/angelhack/service/dto/user/UserSaveRequestDto.java
Labels: feat

#69 Feat/issue56
  src/main/java/org/greenbyme/angelhack/config/SwaggerConfig.java
  src/main/java/org/greenbyme/angelhack/controller/CategoryController.java
  src/main/java/org/greenbyme/angelhack/controller/MissionController.java
  src/main/java/org/greenbyme/angelhack/domain/PeriodScheduler.java
  src/main/java/org/greenbyme/angelhack/service/CategoryService.java
  src/main/java/org/greenbyme/angelhack/service/dto/category/CategoryResDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/category/DayCategoryResDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/category/MissionCertificateCountResDto.java
Labels: feat

#72 #64 Refactor API
  src/main/java/org/greenbyme/angelhack/controller/PostController.java
  src/main/java/org/greenbyme/angelhack/controller/UserController.java
  src/main/java/org/greenbyme/angelhack/service/PostService.java
  src/main/java/org/greenbyme/angelhack/service/UserService.java
  src/main/java/org/greenbyme/angelhack/service/dto/post/PostSaveRequestDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/post/PostUpdateRequestDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/user/UserUpdateNicktDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/user/UserUpdatePhotoDto.java
Labels: feat, fix

#73 Refactor Domain
  src/main/java/org/greenbyme/angelhack/InitDB.java
  src/main/java/org/greenbyme/angelhack/controller/PostController.java
  src/main/java/org/greenbyme/angelhack/domain/mission/Mission.java
  src/main/java/org/greenbyme/angelhack/domain/missionInfo/MissionInfo.java
  src/main/java/org/greenbyme/angelhack/domain/post/Post.java
  src/main/java/org/greenbyme/angelhack/domain/postlike/PostLike.java
  src/main/java/org/greenbyme/angelhack/domain/postlike/PostLikeRepository.java
  src/main/java/org/greenbyme/angelhack/domain/user/User.java
  src/main/java/org/greenbyme/angelhack/service/PostService.java
  src/main/java/org/greenbyme/angelhack/service/dto/mission/MissionDetailsDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/mission/MissionFindAllByCategoryAndDayCategoryResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/mission/MissionFindAllResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/mission/MissionPopularResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/mission/MissionSaveRequestDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/InProgressResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/MissionAndMissionDetailsDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/post/PostDetailResponseDto.java
Labels: fix

#77 Feat/59
  src/main/java/org/greenbyme/angelhack/controller/MissionController.java
  src/main/java/org/greenbyme/angelhack/controller/MissionInfoController.java
  src/main/java/org/greenbyme/angelhack/controller/PageController.java
  src/main/java/org/greenbyme/angelhack/controller/PostController.java
  src/main/java/org/greenbyme/angelhack/domain/missionInfo/MissionInfoRepository.java
  src/main/java/org/greenbyme/angelhack/domain/post/PostRepository.java
  src/main/java/org/greenbyme/angelhack/service/MissionInfoService.java
  src/main/java/org/greenbyme/angelhack/service/PageService.java
  src/main/java/org/greenbyme/angelhack/service/PostService.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/InProgressResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/page/HomePageDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/page/PageDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/post/PostResponseDto.java
Labels: feat, fix

#82 feat: #52 Create Token Refresh API
  src/main/java/org/greenbyme/angelhack/config/security/SecurityConfig.java
  src/main/java/org/greenbyme/angelhack/controller/UserController.java
  src/main/java/org/greenbyme/angelhack/service/UserService.java
  src/main/java/org/greenbyme/angelhack/util/JwtTokenProvider.java
Labels: feat

#83 Release 0_3_0
  src/main/java/org/greenbyme/angelhack/InitDB.java
  src/main/java/org/greenbyme/angelhack/controller/CategoryController.java
  src/main/java/org/greenbyme/angelhack/controller/MissionController.java
  src/main/java/org/greenbyme/angelhack/controller/MissionInfoController.java
  src/main/java/org/greenbyme/angelhack/controller/PageController.java
  src/main/java/org/greenbyme/angelhack/controller/PersonalMissionController.java
  src/main/java/org/greenbyme/angelhack/controller/PostController.java
  src/main/java/org/greenbyme/angelhack/controller/UserController.java
  src/main/java/org/greenbyme/angelhack/domain/Category/Category.java
  src/main/java/org/greenbyme/angelhack/domain/PeriodScheduler.java
  src/main/java/org/greenbyme/angelhack/domain/missionInfo/MissionInfoJPQL.java
  src/main/java/org/greenbyme/angelhack/domain/missionInfo/MissionInfoJPQLImpl.java
  src/main/java/org/greenbyme/angelhack/domain/missionInfo/MissionInfoRepository.java
  src/main/java/org/greenbyme/angelhack/domain/missionInfo/MissionInfoStatus.java
  src/main/java/org/greenbyme/angelhack/domain/personalmission/PersonalMission.java
  src/main/java/org/greenbyme/angelhack/domain/personalmission/PersonalMissionJPQL.java
  src/main/java/org/greenbyme/angelhack/domain/personalmission/PersonalMissionJPQLImpl.java
  src/main/java/org/greenbyme/angelhack/domain/personalmission/PersonalMissionRepository.java
  src/main/java/org/greenbyme/angelhack/domain/personalmission/PersonalMissionStatus.java
  src/main/java/org/greenbyme/angelhack/domain/personalmission/RemainPeriod.java
  src/main/java/org/greenbyme/angelhack/domain/post/Post.java
  src/main/java/org/greenbyme/angelhack/domain/post/PostRepository.java
  src/main/java/org/greenbyme/angelhack/domain/postlike/PostLike.java
  src/main/java/org/greenbyme/angelhack/domain/user/User.java
  src/main/java/org/greenbyme/angelhack/exception/ErrorCode.java
  src/main/java/org/greenbyme/angelhack/exception/PersonalMissionException.java
  src/main/java/org/greenbyme/angelhack/service/MissionInfoService.java
  src/main/java/org/greenbyme/angelhack/service/MissionService.java
  src/main/java/org/greenbyme/angelhack/service/PageService.java
  src/main/java/org/greenbyme/angelhack/service/PersonalMissionService.java
  src/main/java/org/greenbyme/angelhack/service/PostService.java
  src/main/java/org/greenbyme/angelhack/service/UserService.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/InProgressResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/MissionInfoDeleteResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/MissionInfoDetailDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/MissionInfoDetailResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/MissionInfoSaveResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/missionInfo/MissionInfobyUserDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/page/CertPageDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/page/HomePageDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/page/MyPageDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/page/PageDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/page/ProgressMissionInfoDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/page/ProgressPersonalMissionDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/personalmission/InProgressResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/personalmission/MissionAndMissionDetailsDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/personalmission/PersonalMissionByUserDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/personalmission/PersonalMissionDeleteResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/personalmission/PersonalMissionDetailDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/personalmission/PersonalMissionDetailResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/personalmission/PersonalMissionSaveResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/post/PostResponseDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/post/PostSaveRequestDto.java
  src/main/java/org/greenbyme/angelhack/service/dto/user/UserDetailResponseDto.java
Labels: feat

#90 #87
  src/main/java/org/greenbyme/angelhack/service/dto/personalmission/InProgressResponseDto.java
Labels: fix

#91 Refactor Token API
  src/main/java/org/greenbyme/angelhack/controller/UserController.java
  src/main/java/org/greenbyme/angelhack/exception/ErrorCode.java
  src/main/java/org/greenbyme/angelhack/service/PostService.java
  src/main/java/org/greenbyme/angelhack/service/UserService.java
  src/main/java/org/greenbyme/angelhack/service/dto/TokenResponse.java
  src/main/java/org/greenbyme/angelhack/service/dto/post/PostSaveResponseDto.java
Labels: fix, hotfix

#96 Feat/issue89
  http_response_code/README.md
  src/main/java/org/greenbyme/angelhack/domain/DomainListener.java
  src/main/java/org/greenbyme/angelhack/domain/mission/Mission.java
  src/main/java/org/greenbyme/angelhack/domain/mission/MissionCertificationMethod.java
  src/main/java/org/greenbyme/angelhack/domain/personalmission/PersonalMission.java
  src/main/java/org/greenbyme/angelhack/domain/personalmission/RemainPeriod.java
  src/main/java/org/greenbyme/angelhack/domain/post/Post.java
  src/main/java/org/greenbyme/angelhack/domain/user/User.java
  src/main/java/org/greenbyme/angelhack/domain/user/exception/WrongEmailAccessException.java
  src/main/java/org/greenbyme/angelhack/exception/AlreadyExistsPostException.java
  src/main/java/org/greenbyme/angelhack/exception/BusinessException.java
  src/main/java/org/greenbyme/angelhack/exception/EntityNotFoundException.java
  src/main/java/org/greenbyme/angelhack/exception/ErrorCode.java
  src/main/java/org/greenbyme/angelhack/exception/ErrorResponse.java
  src/main/java/org/greenbyme/angelhack/exception/GlobalExceptionHandler.java
  src/main/java/org/greenbyme/angelhack/exception/InvalidValueException.java
Labels: feat
